"""add manager_id to vacancy model

Revision ID: 5672bb533e3e
Revises: 65764348e598
Create Date: 2026-03-04 18:24:04.279352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5672bb533e3e'
down_revision: Union[str, Sequence[str], None] = '65764348e598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('manager_id', sa.Uuid(), nullable=False))
    op.create_index('idx_vacancy_is_active', 'vacancies', ['is_active'], unique=False)
    op.create_index('idx_vacancy_manager_id', 'vacancies', ['manager_id'], unique=False)
    op.create_foreign_key(None, 'vacancies', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_index('idx_vacancy_manager_id', table_name='vacancies')
    op.drop_index('idx_vacancy_is_active', table_name='vacancies')
    op.drop_column('vacancies', 'manager_id')
    # ### end Alembic commands ###
