"""add hh_manager_id to user model

Revision ID: 79d9bbe87d02
Revises: e93e7a2b5286
Create Date: 2026-03-03 17:31:12.923629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d9bbe87d02'
down_revision: Union[str, Sequence[str], None] = 'e93e7a2b5286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hh_manager_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_hh_manager_id'), 'users', ['hh_manager_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_hh_manager_id'), table_name='users')
    op.drop_column('users', 'hh_manager_id')
    # ### end Alembic commands ###
