"""Initial revision

Revision ID: e93e7a2b5286
Revises: 
Create Date: 2026-03-03 15:38:41.835242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93e7a2b5286'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sensitive_data_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vacancies',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vacancy_is_active', 'vacancies', ['is_active'], unique=False)
    op.create_index('idx_vacancy_manager_id', 'vacancies', ['manager_id'], unique=False)
    op.create_table('responses',
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('hh_response_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'VIEWED', 'REJECTED', name='response_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_response_status', 'responses', ['status'], unique=False)
    op.create_index('idx_response_vacancy_id', 'responses', ['vacancy_id'], unique=False)
    op.create_index('idx_response_vacancy_status', 'responses', ['vacancy_id', 'status'], unique=False)
    op.create_index(op.f('ix_responses_hh_response_id'), 'responses', ['hh_response_id'], unique=True)
    op.create_table('contacts',
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'PHONE', 'TELEGRAM', 'OTHER', name='contact_type'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contact_response_id', 'contacts', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contact_response_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_responses_hh_response_id'), table_name='responses')
    op.drop_index('idx_response_vacancy_status', table_name='responses')
    op.drop_index('idx_response_vacancy_id', table_name='responses')
    op.drop_index('idx_response_status', table_name='responses')
    op.drop_table('responses')
    op.drop_index('idx_vacancy_manager_id', table_name='vacancies')
    op.drop_index('idx_vacancy_is_active', table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
