"""Initial revision

Revision ID: f0e2be40dcfa
Revises: 
Create Date: 2026-03-04 15:22:32.547406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e2be40dcfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_to_response_resume',
    sa.Column('vacancy_id', sa.String(length=255), nullable=False),
    sa.Column('response_resume_id', sa.String(length=255), nullable=False),
    sa.Column('hh_response_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('vacancy_id', 'response_resume_id', 'hh_response_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_to_response_resume')
    # ### end Alembic commands ###
